services:
  postgres:
    image: postgres:15-alpine
    container_name: db-todo
    restart: always
    env_file:
      - .env_db
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: