"""Added longest streaks and last active date

Revision ID: 4ead0068f5b1
Revises: 79fbd9de33e5
Create Date: 2025-02-15 22:57:55.535322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ead0068f5b1'
down_revision: Union[str, None] = '79fbd9de33e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_items', sa.Column('longest_streak', sa.Integer(), nullable=True))
    op.add_column('todo_items', sa.Column('last_activity_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('last_activity_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_activity_date')
    op.drop_column('todo_items', 'last_activity_date')
    op.drop_column('todo_items', 'longest_streak')
    # ### end Alembic commands ###
