"""Add total_time_spent, cur_streak to todo model

Revision ID: 79fbd9de33e5
Revises: d73804355bae
Create Date: 2025-01-26 15:24:49.992963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79fbd9de33e5'
down_revision: Union[str, None] = 'd73804355bae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_items', sa.Column('total_time_spent', sa.Integer(), nullable=True))
    op.add_column('todo_items', sa.Column('current_streak', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo_items', 'current_streak')
    op.drop_column('todo_items', 'total_time_spent')
    # ### end Alembic commands ###
